language: php

php:
  - 7.0

env:
  - DB=mysql

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - chmod -R ug+rwx storage bootstrap/cache
  - mysql -e 'create database testing;' -uroot
  - php artisan migrate:install --no-interaction -vvv

script:
 - php artisan migrate --env="testing" --no-interaction -vvv
 - php artisan db:seed --env="testing" --no-interaction -vvv
 - vendor/bin/phpunit


after_script:
  - ls -laR storage
  - cat storage/logs/*