language: php

php:
  - 7.0

env:
  - DB=mysql

dist: trusty
sudo: required
services:
  - mysql

install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  - sudo apt-get update -q
  - sudo apt-get install -q google-chrome-stable

before_script:
  - bash .travis_install-selenium.sh
  - bash .travis_install-mysql-5.7.sh
  - mysql -V
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - chmod -R ug+rwx storage bootstrap/cache
  - sudo mysql -e 'create database testing;' --user=root
  - php artisan key:generate --no-interaction -vvv
  - php artisan migrate:install --no-interaction -vvv


script:
 - php artisan migrate --env="testing" --no-interaction -vvv
 - php artisan db:seed --env="testing" --no-interaction -vvv
 - vendor/bin/phpunit


after_script:
  - ls -laR storage
  - cat storage/logs/*