language: php

php:
  - 7.0

services:
  - mysql

before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit